{"name": "test_divide", "status": "failed", "statusDetails": {"message": "AssertionError: assert (5 / 4) == 1", "trace": "@pytest.mark.arithmetic\n    def test_divide():\n>       assert 5 / 4 == 1\nE       assert (5 / 4) == 1\n\ntest_arithmetic.py:25: AssertionError"}, "start": 1691455704028, "stop": 1691455704028, "uuid": "88c95ebb-5336-4149-9e06-5024e5ff5ff5", "historyId": "a2524f4e0d23e9d1756d6293ab019b23", "testCaseId": "4a9e3f3ed3d8f7414b20a61fd3a33cf0", "fullName": "test_arithmetic#test_divide", "labels": [{"name": "tag", "value": "arithmetic"}, {"name": "suite", "value": "test_arithmetic"}, {"name": "host", "value": "test-users-MacBook-Air.local"}, {"name": "thread", "value": "92021-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_arithmetic"}]}